## Metadata

# 1. METADATA FILE
# Path to sample file
metadata: ./config/samplesheet.csv

# 2. GENOME REFERENCE INFORMATION
reference:  
    # Path to reference genome in fasta format
    fasta: /fdb/GATK_resource_bundle/hg38/Homo_sapiens_assembly38.fasta
    dict: /fdb/GATK_resource_bundle/hg38/Homo_sapiens_assembly38.dict

# Path to known sites
known_sites:
    - "/fdb/GATK_resource_bundle/hg38/dbsnp_146.hg38.vcf.gz"
    - "/fdb/GATK_resource_bundle/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    - "/fdb/GATK_resource_bundle/hg38/1000G_omni2.5.hg38.vcf.gz"
    - "/fdb/GATK_resource_bundle/hg38/hapmap_3.3.hg38.vcf.gz"
    - "/fdb/GATK_resource_bundle/hg38/Homo_sapiens_assembly38.known_indels.vcf.gz"
    - "/fdb/GATK_resource_bundle/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

# 3. BWA DATABASE    
bwadb: 
    # Path to bwa database (set bwa_db: None if a new db has to be generated)
    #path: /fdb/bwa-mem2/hg38/
    path: None

# 4. READ FILES
# Path to raw reads directory (fastq files) 
reads: data/reads
# Set paired to False if single-end reads are used
paired: True

# 5. TRIMMING
# Perform trimming [True, False]
trimming: True
# Path to trimming adapters file
adapters: data/adapters/adapters.fa


##### Wildcard constraints #####
wildcard_constraints:
    vartype="snvs|indels"